apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-dependency
  namespace: argocd-demo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: argocd-demo
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-dependency
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
